# SETTINGS FILE
#
# This file needs to be configured by the user before running the application.

# Data storage location
upload_folder: '_data/uploads'
generated_data_folder: '_data/generated'

# OpenRouter settings
models:
  Summarize-Primary: 'mistralai/ministral-8b'

# Text processing settings
target_word_count_per_batch: 500
min_topics_per_batch: 3
max_topics_per_batch: 5
