# SETTINGS FILE
#
# This file needs to be configured by the user before running the application.

# OpenRouter settings
models:
  Summarize-Primary: 'perplexity/llama-3.1-sonar-large-128k-chat'

# Text processing settings
target_word_count_per_batch: 500
min_topics_per_batch: 10
max_topics_per_batch: 20
