# SETTINGS FILE
#
# This file needs to be configured by the user before running the application.

# OpenRouter settings
models:
  Summarize-Primary: 'mistralai/ministral-8b'

# Text processing settings
target_word_count_per_batch: 500
min_topics_per_batch: 3
max_topics_per_batch: 5
